name: country_picker
description: new flutter project for copertino country picker

publish_to: none #prevent publishing of example app 

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_country: 
    path: ../

    
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
