name: flutter_country
description: 'A lite flutter package for providing world Country Data without
  internet connection, useful for country or language selector '
version: 0.1.3
homepage: https://github.com/egyleader/flutter_country.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  test: ^1.17.12

dev_dependencies: 
  lints: ^1.0.1 


